/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/l.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function MainScene(props: any) {
  const { nodes, materials } = useGLTF('/models/l.glb') as any;
  return (
    <group {...props} dispose={null}>
      <group position={[-0.002, -0.278, -0.03]} rotation={[-Math.PI / 2, 0, 0]} scale={3.375}>
        <mesh geometry={nodes.Object_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_1_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_1_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_1_3.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_1_4.geometry} material={materials.acera} />
        <mesh geometry={nodes.Object_1_5.geometry} material={materials.pabimento} />
      </group>
      <group position={[-8.738, -4.087, 8.696]} rotation={[-Math.PI / 2, 0, -0.065]} scale={0.774}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_20.geometry} material={materials.big_thing} position={[-0.854, 7.909, -0.006]} rotation={[0, -1.571, 0]} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.big_thing} position={[0, 8.705, 0.857]} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.plates} position={[0, 6.596, 0]} rotation={[0, -1.571, 0]} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.big_things} position={[0, 1, 0]} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.little_stuff} position={[-0.475, 7.69, -0.002]} rotation={[0, -1.571, 0]} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.light_thing_1} position={[0, 9.513, 0.968]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.light_thing_1} position={[0, 8.742, 0.968]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.light_thing_1} position={[0, 7.99, 0.968]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.light_thing_1} position={[-0.964, 8.717, -0.006]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.light_thing_1} position={[-0.964, 7.946, -0.006]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_28.geometry} material={materials.light_thing_1} position={[-0.964, 7.193, -0.006]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_34.geometry} material={materials.emmis} position={[-1.026, 8.718, -0.007]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.little_light_things} position={[0, 5.606, 0.656]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.knopkes_mini} position={[0, 7.111, 0]} rotation={[Math.PI / 2, 0, 0.828]} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.bottom_shitngs} position={[0, -0.901, 0]} rotation={[Math.PI / 2, 0, 0.727]} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.many_bolts_nad_lnopkes} position={[-0.975, 8.987, -0.276]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        </group>
      </group>
      <group position={[8.686, -4.076, -9.382]} rotation={[-Math.PI / 2, 0, -3.119]} scale={0.774}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_20001.geometry} material={materials.big_thing} position={[-0.854, 7.909, -0.006]} rotation={[0, -1.571, 0]} />
          <mesh geometry={nodes.Object_10001.geometry} material={materials.big_thing} position={[0, 8.705, 0.857]} />
          <mesh geometry={nodes.Object_32001.geometry} material={materials.plates} position={[0, 6.596, 0]} rotation={[0, -1.571, 0]} />
          <mesh geometry={nodes.Object_4001.geometry} material={materials.big_things} position={[0, 1, 0]} />
          <mesh geometry={nodes.Object_12001.geometry} material={materials.little_stuff} position={[-0.475, 7.69, -0.002]} rotation={[0, -1.571, 0]} />
          <mesh geometry={nodes.Object_14001.geometry} material={materials.light_thing_1} position={[0, 9.513, 0.968]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_16001.geometry} material={materials.light_thing_1} position={[0, 8.742, 0.968]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_18001.geometry} material={materials.light_thing_1} position={[0, 7.99, 0.968]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_22001.geometry} material={materials.light_thing_1} position={[-0.964, 8.717, -0.006]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_26001.geometry} material={materials.light_thing_1} position={[-0.964, 7.946, -0.006]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_28001.geometry} material={materials.light_thing_1} position={[-0.964, 7.193, -0.006]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_34001.geometry} material={materials.emmis} position={[-1.026, 8.718, -0.007]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Object_8001.geometry} material={materials.little_light_things} position={[0, 5.606, 0.656]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_6001.geometry} material={materials.knopkes_mini} position={[0, 7.111, 0]} rotation={[Math.PI / 2, 0, 0.828]} />
          <mesh geometry={nodes.Object_30001.geometry} material={materials.bottom_shitngs} position={[0, -0.901, 0]} rotation={[Math.PI / 2, 0, 0.727]} />
          <mesh geometry={nodes.Object_24001.geometry} material={materials.many_bolts_nad_lnopkes} position={[-0.975, 8.987, -0.276]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        </group>
      </group>
      <group position={[-8.928, -4.087, 111.2]} rotation={[-Math.PI / 2, 0, -0.065]} scale={0.774}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_20002.geometry} material={materials.big_thing} position={[-0.854, 7.909, -0.006]} rotation={[0, -1.571, 0]} />
          <mesh geometry={nodes.Object_10002.geometry} material={materials.big_thing} position={[0, 8.705, 0.857]} />
          <mesh geometry={nodes.Object_32002.geometry} material={materials.plates} position={[0, 6.596, 0]} rotation={[0, -1.571, 0]} />
          <mesh geometry={nodes.Object_4002.geometry} material={materials.big_things} position={[0, 1, 0]} />
          <mesh geometry={nodes.Object_12002.geometry} material={materials.little_stuff} position={[-0.475, 7.69, -0.002]} rotation={[0, -1.571, 0]} />
          <mesh geometry={nodes.Object_14002.geometry} material={materials.light_thing_1} position={[0, 9.513, 0.968]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_16002.geometry} material={materials.light_thing_1} position={[0, 8.742, 0.968]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_18002.geometry} material={materials.light_thing_1} position={[0, 7.99, 0.968]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_22002.geometry} material={materials.light_thing_1} position={[-0.964, 8.717, -0.006]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_26002.geometry} material={materials.light_thing_1} position={[-0.964, 7.946, -0.006]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_28002.geometry} material={materials.light_thing_1} position={[-0.964, 7.193, -0.006]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_34002.geometry} material={materials.emmis} position={[-1.026, 8.718, -0.007]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Object_8002.geometry} material={materials.little_light_things} position={[0, 5.606, 0.656]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_6002.geometry} material={materials.knopkes_mini} position={[0, 7.111, 0]} rotation={[Math.PI / 2, 0, 0.828]} />
          <mesh geometry={nodes.Object_30002.geometry} material={materials.bottom_shitngs} position={[0, -0.901, 0]} rotation={[Math.PI / 2, 0, 0.727]} />
          <mesh geometry={nodes.Object_24002.geometry} material={materials.many_bolts_nad_lnopkes} position={[-0.975, 8.987, -0.275]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        </group>
      </group>
      <group position={[8.496, -4.076, 93.122]} rotation={[-Math.PI / 2, 0, -3.119]} scale={0.774}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_20003.geometry} material={materials.big_thing} position={[-0.854, 7.909, -0.006]} rotation={[0, -1.571, 0]} />
          <mesh geometry={nodes.Object_10003.geometry} material={materials.big_thing} position={[0, 8.705, 0.857]} />
          <mesh geometry={nodes.Object_32003.geometry} material={materials.plates} position={[0, 6.596, 0]} rotation={[0, -1.571, 0]} />
          <mesh geometry={nodes.Object_4003.geometry} material={materials.big_things} position={[0, 1, 0]} />
          <mesh geometry={nodes.Object_12003.geometry} material={materials.little_stuff} position={[-0.475, 7.69, -0.002]} rotation={[0, -1.571, 0]} />
          <mesh geometry={nodes.Object_14003.geometry} material={materials.light_thing_1} position={[0, 9.513, 0.968]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_16003.geometry} material={materials.light_thing_1} position={[0, 8.742, 0.968]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_18003.geometry} material={materials.light_thing_1} position={[0, 7.99, 0.968]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_22003.geometry} material={materials.light_thing_1} position={[-0.964, 8.717, -0.006]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_26003.geometry} material={materials.light_thing_1} position={[-0.964, 7.946, -0.006]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_28003.geometry} material={materials.light_thing_1} position={[-0.964, 7.193, -0.006]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Object_34003.geometry} material={materials.emmis} position={[-1.026, 8.718, -0.007]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Object_8003.geometry} material={materials.little_light_things} position={[0, 5.606, 0.656]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_6003.geometry} material={materials.knopkes_mini} position={[0, 7.111, 0]} rotation={[Math.PI / 2, 0, 0.828]} />
          <mesh geometry={nodes.Object_30003.geometry} material={materials.bottom_shitngs} position={[0, -0.901, 0]} rotation={[Math.PI / 2, 0, 0.727]} />
          <mesh geometry={nodes.Object_24003.geometry} material={materials.many_bolts_nad_lnopkes} position={[-0.975, 8.987, -0.275]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('public/models/l.glb')
